// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Common;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240207175335_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Urls.ShortenedUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShortenedUrls", "dbo");
                });

            modelBuilder.Entity("Infrastructure.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d8bf67d-3ef3-4d1f-a7e5-31e5c6cffc46"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c448c1f-22ba-4ff5-952d-09459f43da7d",
                            Email = "Larry.Olson49@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "larry.olson49@gmail.com",
                            NormalizedUserName = "LARRY84",
                            PasswordHash = "AQAAAAIAAYagAAAAEPv7WaANiwa5F3XF+pDpepv3IMYMieHEMcYUoKN9vbVTxgnrBtDQczuowcDqIje0FQ==",
                            PhoneNumber = "724.496.2761 x5091",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Larry84"
                        },
                        new
                        {
                            Id = new Guid("8e60fb34-99d6-431a-a998-98f2056637e5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2db55283-7717-4386-9bd3-55f87b9673c9",
                            Email = "Marcia.Cummings@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "marcia.cummings@hotmail.com",
                            NormalizedUserName = "MARCIA.CUMMINGS",
                            PasswordHash = "AQAAAAIAAYagAAAAECCspQvKb+LPRR47rVQtMkyIxQRoLbDCZoWcgth9NkW8WeKiLsU5K8jKmr0fzkgBBg==",
                            PhoneNumber = "1-844-290-6181 x0660",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Marcia.Cummings"
                        },
                        new
                        {
                            Id = new Guid("b519017e-f722-4272-9a16-3be1348800d3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d547da36-5a6c-4b38-b67e-a28f9190b5e2",
                            Email = "Rose31@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "rose31@yahoo.com",
                            NormalizedUserName = "ROSE.PROHASKA",
                            PasswordHash = "AQAAAAIAAYagAAAAELnQFBBIpJBmk5KjaXwW1BMb1nfkuZSV64RjuPfkuqgVtBaNLAML5pxNcbydt90bTQ==",
                            PhoneNumber = "236-718-9551",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Rose.Prohaska"
                        },
                        new
                        {
                            Id = new Guid("93d1e03d-40a6-40f7-91ae-99b28771298d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be0577db-05a4-4e8f-9aa5-dc53e97e715c",
                            Email = "Amos34@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "amos34@gmail.com",
                            NormalizedUserName = "AMOS_ONDRICKA13",
                            PasswordHash = "AQAAAAIAAYagAAAAEB4Th9BlnBldG/XAcCM+47SgXfOOPr4LX6Dfo96GEwRpN39gKoCtrgplOGu0lXTxfw==",
                            PhoneNumber = "1-775-880-4120",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Amos_Ondricka13"
                        },
                        new
                        {
                            Id = new Guid("f3f68f7f-b91a-45f2-a5ea-e8b08ca00c6a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c3b5821-bc1b-4600-81c8-9fd00d0ff53c",
                            Email = "Lindsey.Rowe68@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "lindsey.rowe68@yahoo.com",
                            NormalizedUserName = "LINDSEY.ROWE",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDksAFadUFxvCchOgYIM/WYMOWi8n5Nb98FvCe///LqWopM7blNPiHIUQu/uFGJ+g==",
                            PhoneNumber = "821-341-2454 x953",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Lindsey.Rowe"
                        },
                        new
                        {
                            Id = new Guid("f02b2137-b1bb-44c0-bd3c-8d339374b3a9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4054a0a-f8ff-4268-b298-4e3ac021cda9",
                            Email = "Betty_Kreiger50@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "betty_kreiger50@hotmail.com",
                            NormalizedUserName = "BETTY_KREIGER",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUxVRznNs1mA3u55J5yK3L1C6Wfiwnu1tz3v/qa3DxrUWFVJbtb7xG+a5h2hOvSRg==",
                            PhoneNumber = "395-598-1507 x40470",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Betty_Kreiger"
                        },
                        new
                        {
                            Id = new Guid("f6715760-c102-4146-842d-93e15e559d33"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "932a03c7-865f-4a81-aadf-f91fdf27375f",
                            Email = "Flora16@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "flora16@hotmail.com",
                            NormalizedUserName = "FLORA0",
                            PasswordHash = "AQAAAAIAAYagAAAAEAj/QADRwW01VKuuiLaCAmtqfcLy/y78vjHvpsSbTIWBWQDtHBTRUvorczqgsSs4lg==",
                            PhoneNumber = "988-708-7380",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Flora0"
                        },
                        new
                        {
                            Id = new Guid("216de5f7-d870-4322-889e-d76ccfeb704e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e912a5e4-677a-428c-8eb4-9757fdd21f6b",
                            Email = "Javier30@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "javier30@gmail.com",
                            NormalizedUserName = "JAVIER_ALTENWERTH30",
                            PasswordHash = "AQAAAAIAAYagAAAAECOYCTcgGBSmJcGlprae9sLqeXt4VeFygm38KKszWUtsmaWTELznpCUui97clzU5rQ==",
                            PhoneNumber = "(484) 459-3709 x777",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Javier_Altenwerth30"
                        },
                        new
                        {
                            Id = new Guid("5364b40a-3d12-49d9-bf39-a13eab8e62eb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "978e6a36-383a-4db4-b66e-8131369cd8fd",
                            Email = "Bruce_Hamill@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "bruce_hamill@hotmail.com",
                            NormalizedUserName = "BRUCE.HAMILL",
                            PasswordHash = "AQAAAAIAAYagAAAAEJxhlQxpoRoLCC1SbmGDOkYlkTdenpz0z6W95OZZ1XMFwVj2DoMmPwVW0DB0PxvmLw==",
                            PhoneNumber = "1-325-378-2827",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Bruce.Hamill"
                        },
                        new
                        {
                            Id = new Guid("1feba27c-e47e-4a40-af0a-7d403bd86831"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26d7c768-056a-44e9-93e8-4770b5b3b77b",
                            Email = "Sally_Roberts@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "sally_roberts@yahoo.com",
                            NormalizedUserName = "SALLY5",
                            PasswordHash = "AQAAAAIAAYagAAAAEMuZGivLi0GDHZ20EkrAMWtoBCrJR/xPZ/H2sKmSePiQxCW+XpNMZ0/HGkU8izNiyQ==",
                            PhoneNumber = "962-420-9034 x8288",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Sally5"
                        },
                        new
                        {
                            Id = new Guid("20d382b5-112e-4dc4-9d01-4002aa99bd82"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a6767f69-db77-4367-b278-29be0d405ce1",
                            Email = "Jacquelyn_Price64@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "jacquelyn_price64@hotmail.com",
                            NormalizedUserName = "JACQUELYN_PRICE",
                            PasswordHash = "AQAAAAIAAYagAAAAEL42LSsItAQ8bOuU3+gLzW9qYGZZXAIpylyptz7IAx8ZI/xTVFUPkbulBFgxJcomQA==",
                            PhoneNumber = "268.207.4767",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Jacquelyn_Price"
                        },
                        new
                        {
                            Id = new Guid("2f42088a-4ce4-4571-81fd-da89d01d526d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc2c7468-f2fd-4979-8233-520f0cfb6675",
                            Email = "Dawn.Wisoky@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "dawn.wisoky@hotmail.com",
                            NormalizedUserName = "DAWN80",
                            PasswordHash = "AQAAAAIAAYagAAAAEK4jDmyhnhLQ/5pG6xymAKARnD1qNmwA/B36Wy3sg9mwkOF6+Ht4RBp1uTIgnc9fJQ==",
                            PhoneNumber = "(247) 770-2215",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Dawn80"
                        },
                        new
                        {
                            Id = new Guid("7f4144c7-ecc1-474d-82e1-ccfed60ab046"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e56c0c61-5f43-4720-b223-dae36b57a023",
                            Email = "Teresa.Senger75@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "teresa.senger75@yahoo.com",
                            NormalizedUserName = "TERESA60",
                            PasswordHash = "AQAAAAIAAYagAAAAEPnIkzaAEYHP7Ls3yxviJCjdwX0p81jo1GXi9gHGkp10F16PEyamZBvkantr5lqQRg==",
                            PhoneNumber = "531-923-0906 x69255",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Teresa60"
                        },
                        new
                        {
                            Id = new Guid("0aa1978e-4735-4ea0-95d1-9076202fb78e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d503e874-0121-4659-8107-ffa481a4acea",
                            Email = "Lena.Hettinger9@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "lena.hettinger9@gmail.com",
                            NormalizedUserName = "LENA44",
                            PasswordHash = "AQAAAAIAAYagAAAAEPI/tUtqRt7LOA3AfTqXY0G+o3UJn4SrNVbgWKZMipD+1NMHFqwtQ2Ihx8bHcxF1tQ==",
                            PhoneNumber = "(203) 467-0180",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Lena44"
                        },
                        new
                        {
                            Id = new Guid("c94de392-9d6c-4870-9ff9-0cf7effa6dfb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24350132-22fb-49c2-90d3-72c8e66db270",
                            Email = "Donna_Koelpin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "donna_koelpin@gmail.com",
                            NormalizedUserName = "DONNA.KOELPIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELSLLwqR/ZalUmXC33ti7u04jY5G5mpIfqawbtRxgFbP2JK3ACE805bUGHhOlPy9SA==",
                            PhoneNumber = "(494) 304-2722 x2977",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Donna.Koelpin"
                        },
                        new
                        {
                            Id = new Guid("98376387-6597-49f2-a3cc-2e5c9167a3c3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce5c496a-3c2a-415b-b420-6f32ecff4abd",
                            Email = "Alan27@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "alan27@gmail.com",
                            NormalizedUserName = "ALAN.WINDLER41",
                            PasswordHash = "AQAAAAIAAYagAAAAEED0FKHHM9ytW7QSmOsBYMym1k22IpfqyEX5GBhLTDdbhzpy4VteMIbt+xP/17k86w==",
                            PhoneNumber = "953.646.4029 x20727",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Alan.Windler41"
                        },
                        new
                        {
                            Id = new Guid("c769fbaa-89cf-445d-83f4-870429fe4ae4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ece92080-dd11-450e-84f1-f33e3c05e9ad",
                            Email = "Estelle.Nolan82@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "estelle.nolan82@yahoo.com",
                            NormalizedUserName = "ESTELLE_NOLAN6",
                            PasswordHash = "AQAAAAIAAYagAAAAEPloKqBvN2TeH21T7hoyTbRA9UJTVm6Npdi02J7LWQeiEPmY8TmMg+VUoujYHZOhJw==",
                            PhoneNumber = "(786) 466-3356 x4791",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Estelle_Nolan6"
                        },
                        new
                        {
                            Id = new Guid("29f73729-e11a-4aac-b394-579f26079d99"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e63c8b6-2e18-4e50-b518-40f0866fa380",
                            Email = "Marvin75@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "marvin75@yahoo.com",
                            NormalizedUserName = "MARVIN_LEBSACK",
                            PasswordHash = "AQAAAAIAAYagAAAAECDDQ3ZOiqU2KFnFNAPT3Rn0afWVcBLGN07ygCWyg7OL5hfQ2Khq4jJ/09J5oIgt+g==",
                            PhoneNumber = "344-229-3559 x5831",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Marvin_Lebsack"
                        },
                        new
                        {
                            Id = new Guid("f73a2980-0e62-410f-95a4-31ea798ccb60"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "175128a2-e9b6-4fa4-a3e4-34a97abfeaba",
                            Email = "Amos_Brakus86@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "amos_brakus86@yahoo.com",
                            NormalizedUserName = "AMOS_BRAKUS18",
                            PasswordHash = "AQAAAAIAAYagAAAAEHpl1VpIAaB5gxhq2CdvPrmU4ngtWikU1g6hGWqCmpgiK69f8nrpgVHxaVlyyJTFuQ==",
                            PhoneNumber = "1-805-392-1449",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Amos_Brakus18"
                        },
                        new
                        {
                            Id = new Guid("d3869961-ffa7-418b-8d89-ca64d92a1e5c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce6105bf-586d-4c40-a1ee-1d2fe3de3db7",
                            Email = "Barry_Williamson@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "barry_williamson@hotmail.com",
                            NormalizedUserName = "BARRY19",
                            PasswordHash = "AQAAAAIAAYagAAAAEPtVcXLhF2TOGNyjorj2gHs26mzztK6+S+1wKhljOF7LmCoTlLE0YIK9VfjhRzhv0A==",
                            PhoneNumber = "(804) 600-0539",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Barry19"
                        },
                        new
                        {
                            Id = new Guid("b6961019-a5b0-43de-966a-9206189bd39d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f56d69da-6462-47e9-8a6d-4fdefd427134",
                            Email = "Darrel81@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "darrel81@gmail.com",
                            NormalizedUserName = "DARREL72",
                            PasswordHash = "AQAAAAIAAYagAAAAEHMgxWYuvfS/dzgz4pCZiXk7EpqE1VZwWyo8AA/4qqVuv5tsFVJWiMktfhOv3cacZw==",
                            PhoneNumber = "(259) 210-9100 x196",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Darrel72"
                        },
                        new
                        {
                            Id = new Guid("adc4fa42-6529-4b55-95c1-6f548b1bc90b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa7fa545-2a21-4337-86f2-7b4f7180c2da",
                            Email = "Lawrence_Breitenberg93@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "lawrence_breitenberg93@hotmail.com",
                            NormalizedUserName = "LAWRENCE53",
                            PasswordHash = "AQAAAAIAAYagAAAAEDcU5YlSs+cQ+p0LgWGykebTfegD6Lb9vTGKi6/XiXrzUR4tw91/ic73jsJANPaDxg==",
                            PhoneNumber = "743.968.5873",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Lawrence53"
                        },
                        new
                        {
                            Id = new Guid("067d5760-6870-43e4-a70a-1919328b6c3d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea43bc44-97fa-4df5-803e-f90caca59742",
                            Email = "Barbara_Wilkinson@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "barbara_wilkinson@gmail.com",
                            NormalizedUserName = "BARBARA_WILKINSON71",
                            PasswordHash = "AQAAAAIAAYagAAAAECWVHDOSHN1njWME06R/5J08EVfQk8P6giGGkhW8q98zQh1VQgpwVfxEMv6k4+mbMA==",
                            PhoneNumber = "573.337.8260 x2525",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Barbara_Wilkinson71"
                        },
                        new
                        {
                            Id = new Guid("1b99dab5-4c19-47fa-9134-2909fe275bd1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1fa64d3d-df73-4dcf-82b6-5c2e6ae7747a",
                            Email = "Jessie54@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "jessie54@hotmail.com",
                            NormalizedUserName = "JESSIE.BRAKUS12",
                            PasswordHash = "AQAAAAIAAYagAAAAEPt0hU7EvAby5g5ZrTunhJuXkTHL5DGBF7EHy293QD2lPtRRP7s+WMt7C2biTQFK3g==",
                            PhoneNumber = "258.805.2604",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Jessie.Brakus12"
                        },
                        new
                        {
                            Id = new Guid("7cb59167-d4c5-4986-87af-a127d448ed34"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96030483-517c-46fb-88d5-948a5706952d",
                            Email = "Alex53@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "alex53@hotmail.com",
                            NormalizedUserName = "ALEX_KLING",
                            PasswordHash = "AQAAAAIAAYagAAAAEPq/G/MP25cBXA4z2KmTvr2sukyYJT6vqWCa91CB4cUmNNbRGHVndrgVB9JRLs7k9Q==",
                            PhoneNumber = "329.751.6317 x06335",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Alex_Kling"
                        },
                        new
                        {
                            Id = new Guid("621a0a9d-e846-4bd9-b8ad-24d7769b3b1f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcf8ac1a-856d-4170-96a4-5bdf8128b96a",
                            Email = "Constance44@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "constance44@gmail.com",
                            NormalizedUserName = "CONSTANCE81",
                            PasswordHash = "AQAAAAIAAYagAAAAEOfE6sm16HlvFxWiOMc1KHYDG8LT+//1mu3aMbpYmRg8J2zMOrHM4lLI0uBXJNqKoQ==",
                            PhoneNumber = "971.722.0140 x830",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Constance81"
                        },
                        new
                        {
                            Id = new Guid("2c96d7f9-dd29-4d18-9699-c83d7635f095"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "212b1b79-edf7-4bed-a0fb-823c5e4f7a2e",
                            Email = "Julian_Satterfield45@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "julian_satterfield45@gmail.com",
                            NormalizedUserName = "JULIAN21",
                            PasswordHash = "AQAAAAIAAYagAAAAEEwobOkfwPZekagfVDq++pYA5h1zMIPM5QJxlcahi9noPRH3zfJ0NlufpvOxPaHo3g==",
                            PhoneNumber = "(662) 649-0842",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Julian21"
                        },
                        new
                        {
                            Id = new Guid("6b25f231-d4a4-4681-b872-5c57766ff680"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a99ed153-5bd4-480f-a8d8-a27b2c25acab",
                            Email = "Delores.Jast12@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "delores.jast12@yahoo.com",
                            NormalizedUserName = "DELORES_JAST",
                            PasswordHash = "AQAAAAIAAYagAAAAEJvLIjNhbipCwj3MckqGW1LgxZPIWZOIIsiXXnDZLTz5P/EZjdzv3IPH2qhDATow3Q==",
                            PhoneNumber = "372-631-2109 x239",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Delores_Jast"
                        },
                        new
                        {
                            Id = new Guid("04251651-10d2-4032-aa35-d23427b73379"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7fb37a1-8605-46b5-8573-fa6df67e288d",
                            Email = "Gregory24@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "gregory24@gmail.com",
                            NormalizedUserName = "GREGORY20",
                            PasswordHash = "AQAAAAIAAYagAAAAEJMt/8FJpJKTV4/g4GkHExVtcJOOeyYshXiFPKpmGI8/Or9RS7oo/Wdwrgc5W98WSg==",
                            PhoneNumber = "265-433-6338",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Gregory20"
                        },
                        new
                        {
                            Id = new Guid("36eb7772-c3fe-4522-a66c-ae1d2801a613"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "224b0af1-1858-422a-87d7-5ab1f9fbc381",
                            Email = "Jose.Champlin23@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "jose.champlin23@gmail.com",
                            NormalizedUserName = "JOSE.CHAMPLIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPfq8g/oMKw2a4i2klcWxPOu4JqjvIruscSzajtS4x8lbkiZom3htb2TY211xeZuBQ==",
                            PhoneNumber = "(342) 672-6050 x9503",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "Jose.Champlin"
                        },
                        new
                        {
                            Id = new Guid("1d15aad6-28fc-42bc-9ace-1267eb399dab"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96b3a62d-4e87-49f1-a5aa-f9fac360a5d9",
                            Email = "Kristi.Satterfield@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "kristi.satterfield@yahoo.com",
                            NormalizedUserName = "KRISTI76",
                            PasswordHash = "AQAAAAIAAYagAAAAEL4nX6K1GKo64zbg/kCAYd2idEIZMfA2wBTiBFKiYZlZiFV3l174VCAo7uMoWmH33g==",
                            PhoneNumber = "494.831.8799",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Kristi76"
                        },
                        new
                        {
                            Id = new Guid("4eb4073a-0608-4959-9fcf-166c8d411fd3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "535bcd2f-48d8-4a93-beef-2f237da0d497",
                            Email = "Gail_Kunde25@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "gail_kunde25@gmail.com",
                            NormalizedUserName = "GAIL_KUNDE",
                            PasswordHash = "AQAAAAIAAYagAAAAEIMeVOGR4wErL5hB3UCmWjswUDFiUYS2OIyX47KMVdA4IJzCi2Im8bqDq7FeVLP/TA==",
                            PhoneNumber = "599-555-3634 x896",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Gail_Kunde"
                        },
                        new
                        {
                            Id = new Guid("35300806-43fa-4d03-bb8f-6c2ef525de8a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e7eb083-a5e4-49bb-8686-9ae37d0f6635",
                            Email = "Myra51@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "myra51@hotmail.com",
                            NormalizedUserName = "MYRA81",
                            PasswordHash = "AQAAAAIAAYagAAAAEM9HuYdV+VgW4gnk1uYgsSmHKubxuCxznQAPM2desgvheTbCZUai9awDgWyQjOrTMQ==",
                            PhoneNumber = "627-664-3512 x16494",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Myra81"
                        },
                        new
                        {
                            Id = new Guid("2c305e0a-686c-48b5-bce2-e90c75453244"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10d23b73-3827-4f41-a1cd-9d560a18e70a",
                            Email = "Yvonne60@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "yvonne60@gmail.com",
                            NormalizedUserName = "YVONNE.FARRELL26",
                            PasswordHash = "AQAAAAIAAYagAAAAEBqy4ulF8qz+lSonWvp5z+aJfbF+kxVW+c4EkgfhOhn7alikrG9w3zaJ8gGsGATI8Q==",
                            PhoneNumber = "376.680.7062 x7955",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Yvonne.Farrell26"
                        },
                        new
                        {
                            Id = new Guid("df1f0d4f-4e36-43aa-89bc-33313f1ca451"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbee9ae7-244d-4239-95cf-701891118de6",
                            Email = "Mary.Johnston28@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "mary.johnston28@gmail.com",
                            NormalizedUserName = "MARY_JOHNSTON77",
                            PasswordHash = "AQAAAAIAAYagAAAAEHV34o61ETyrQPJ6RxK/sNI4Sf7nUSzq78muSlpOtmu0D0F52Rej4/W3vELtEEJ3fA==",
                            PhoneNumber = "447-230-8012 x1039",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Mary_Johnston77"
                        },
                        new
                        {
                            Id = new Guid("b054ff81-3080-4dd2-9574-d8f1839231a4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d300281-5d3e-4d53-ac5e-44ec948f3269",
                            Email = "Gregory.Veum75@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "gregory.veum75@gmail.com",
                            NormalizedUserName = "GREGORY.VEUM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIQDSxB5iTjnCBuk4UcPXi1PZuIK2Mzu4ywV/yLgi5wEV+N7jtCHLLXqN1reTJHv0A==",
                            PhoneNumber = "599-735-5443",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Gregory.Veum"
                        },
                        new
                        {
                            Id = new Guid("d25cb5cc-54d0-4773-9938-0de9f812e50e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9eedddbd-79a8-4641-9061-b1116fcb1a9c",
                            Email = "Erica42@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "erica42@gmail.com",
                            NormalizedUserName = "ERICA.GLEASON72",
                            PasswordHash = "AQAAAAIAAYagAAAAENgo0hcbhoXVCLK7OAyi4wwBGGrjtvmw6WB2hqsSnJLAZ6rns4f8IvHyZm6ZztwR2A==",
                            PhoneNumber = "(809) 902-1900",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Erica.Gleason72"
                        },
                        new
                        {
                            Id = new Guid("6936dfce-6c64-44b4-9f11-f316d8d9658d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7dcbf6a-e367-418f-86cc-c2fa02c5a1ed",
                            Email = "Todd8@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "todd8@hotmail.com",
                            NormalizedUserName = "TODD.KULAS",
                            PasswordHash = "AQAAAAIAAYagAAAAEJVOtt3AsnMtsx1H6StGkDTuLLISyZwm6RwesKxdzFmN8wOt+SYAnlboyotqHE0wQQ==",
                            PhoneNumber = "1-229-452-8605",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = true,
                            UserName = "Todd.Kulas"
                        },
                        new
                        {
                            Id = new Guid("9c72d2d6-1dda-44df-9607-929734201210"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "63b57d0e-e888-4b62-8311-8a6c89850cd2",
                            Email = "Salvatore_Runte@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "salvatore_runte@yahoo.com",
                            NormalizedUserName = "SALVATORE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEGXuBy9RN1Taz+iy9NWRohNS6xvyEJGiC+yMacDlnLbZsV2aXHDJgbCxHbU5HvFdXQ==",
                            PhoneNumber = "(318) 233-1973 x2285",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = true,
                            UserName = "Salvatore50"
                        },
                        new
                        {
                            Id = new Guid("80bd319d-819c-444f-b710-1da94bf01b9d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f097139e-b06f-4b7e-9cbe-807575741807",
                            Email = "Hope.Farrell@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "hope.farrell@gmail.com",
                            NormalizedUserName = "HOPE52",
                            PasswordHash = "AQAAAAIAAYagAAAAENdqhkj6ZUC60b19c0hLFjyMcrobb1feDiY9Qm/00I+DDQ8F1j2rJJ5knS0pV/kQeg==",
                            PhoneNumber = "(436) 439-4890 x93587",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Hope52"
                        },
                        new
                        {
                            Id = new Guid("cbe71842-8ed2-4861-a45c-8819ff037af5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "66f4f323-e7ec-4a58-88d3-52dd04b24dae",
                            Email = "Samantha_Ruecker@hotmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "samantha_ruecker@hotmail.com",
                            NormalizedUserName = "SAMANTHA.RUECKER6",
                            PasswordHash = "AQAAAAIAAYagAAAAEKw1Vmemt3d5nnIu3ZDDWb0fi/kigYM0y8z2rQno/7QDNmDxqi5QxAtXpVnJ/R/MLA==",
                            PhoneNumber = "211.522.1344 x2158",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Samantha.Ruecker6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
